spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: askme@sandbox0a0ffc268386452db8be7ab95d80a931.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

askme:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"


logging:
  level:
    com.ruimendes.askme: DEBUG