spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: askme@sandbox0a0ffc268386452db8be7ab95d80a931.mailgun.org # TODO needs to be updated - sandbox key

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

askme:
  email:
    url: "https://askme.ruimendesdev.eu"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://askme.ruimendesdev.eu"