spring:
  application:
    name: askme

  data:
    redis:
      host: "redis-14232.c328.europe-west3-1.gce.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 14232
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://db.dlhcflruahfzcvnggnsj.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: dog.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: bgzyivcp
    ssl:
      enabled: true
    virtual-host: bgzyivcp
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1 # free plan allows only 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}

askme:
  email:
    from: mail@askme-rui.com
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on the same machine
    - "::1" # localhost ipv6
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://dlhcflruahfzcvnggnsj.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}